// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebEtiqueta.Models;

#nullable disable

namespace WebEtiqueta.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20250325121113_atualizaBase")]
    partial class atualizaBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebEtiqueta.Models.EtiquetaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ETIQUETA_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Altura")
                        .HasColumnType("integer")
                        .HasColumnName("ETIQUETA_ALTURA");

                    b.Property<int>("Colunas")
                        .HasColumnType("integer")
                        .HasColumnName("ETIQUETA_COLUNAS");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("boolean")
                        .HasColumnName("ETIQUETA_ELIMINADO");

                    b.Property<DateTime?>("EliminadoData")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ETIQUETA_ELIMINADO_DATA");

                    b.Property<int?>("EliminadoPor")
                        .HasColumnType("integer")
                        .HasColumnName("ETIQUETA_ELIMINADO_POR");

                    b.Property<int>("EspacoX")
                        .HasColumnType("integer")
                        .HasColumnName("ETIQUETA_ESPACOX");

                    b.Property<int>("EspacoY")
                        .HasColumnType("integer")
                        .HasColumnName("ETIQUETA_ESPACOY");

                    b.Property<int>("Largura")
                        .HasColumnType("integer")
                        .HasColumnName("ETIQUETA_LARGURA");

                    b.Property<int>("Linhas")
                        .HasColumnType("integer")
                        .HasColumnName("ETIQUETA_LINHAS");

                    b.Property<int>("MatrizId")
                        .HasColumnType("integer")
                        .HasColumnName("ETIQUETA_MATRIZ_ID");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ETIQUETA_MODELO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ETIQUETA_NOME");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ETIQUETA_TIPO");

                    b.HasKey("Id");

                    b.HasIndex("EliminadoPor");

                    b.HasIndex("MatrizId");

                    b.ToTable("ETIQUETA");
                });

            modelBuilder.Entity("WebEtiqueta.Models.FilialEtiquetaModel", b =>
                {
                    b.Property<int>("FilialId")
                        .HasColumnType("integer")
                        .HasColumnName("FILIAL_ID");

                    b.Property<int>("EtiquetaId")
                        .HasColumnType("integer")
                        .HasColumnName("ETIQUETA_ID");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("boolean")
                        .HasColumnName("DISPONIVEL");

                    b.HasKey("FilialId", "EtiquetaId");

                    b.HasIndex("EtiquetaId");

                    b.ToTable("FILIAL_ETIQUETA");
                });

            modelBuilder.Entity("WebEtiqueta.Models.FilialModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("FILIAL_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CnpjCpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("FILIAL_CPNJ_CPF");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("boolean")
                        .HasColumnName("FILIAL_ELIMINADO");

                    b.Property<DateTime?>("EliminadoData")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FILIAL_ELIMINADO_DATA");

                    b.Property<int?>("EliminadoPor")
                        .HasColumnType("integer")
                        .HasColumnName("FILIAL_ELIMINADO_POR");

                    b.Property<int>("MatrizId")
                        .HasColumnType("integer")
                        .HasColumnName("FILIAL_MATRIZ_ID");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("FILIAL_NOME");

                    b.HasKey("Id");

                    b.HasIndex("EliminadoPor");

                    b.HasIndex("MatrizId");

                    b.ToTable("FILIAL");
                });

            modelBuilder.Entity("WebEtiqueta.Models.MatrizModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("MATRIZ_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CnpjCpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("MATRIZ_CNPJ_CPF");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("MATRIZ_NOME");

                    b.HasKey("Id");

                    b.ToTable("MATRIZ");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CnpjCpf = "00000000000000",
                            Nome = "MATRIZ"
                        },
                        new
                        {
                            Id = 2,
                            CnpjCpf = "00748572000153",
                            Nome = "ARMAZÉM FAVEIRO"
                        });
                });

            modelBuilder.Entity("WebEtiqueta.Models.NivelAcessoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("NIVEL_ACESSO_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AdicionarEtiqueta")
                        .HasColumnType("boolean")
                        .HasColumnName("NIVEL_ACESSO_ADICIONAR_ETIQUETA");

                    b.Property<bool>("AdicionarFilial")
                        .HasColumnType("boolean")
                        .HasColumnName("NIVEL_ACESSO_ADICIONAR_FILIAR");

                    b.Property<bool>("AdicionarUsuario")
                        .HasColumnType("boolean")
                        .HasColumnName("NIVEL_ACESSO_ADICIONAR_USUARIO");

                    b.Property<bool>("EditarEtiqueta")
                        .HasColumnType("boolean")
                        .HasColumnName("NIVEL_ACESSO_EDITAR_ETIQUETA");

                    b.Property<bool>("EditarFilial")
                        .HasColumnType("boolean")
                        .HasColumnName("NIVEL_ACESSO_EDITAR_FILIAR");

                    b.Property<bool>("EditarUsuario")
                        .HasColumnType("boolean")
                        .HasColumnName("NIVEL_ACESSO_EDITAR_USUARIO");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("boolean")
                        .HasColumnName("NIVEL_ACESSO_ELIMINADO");

                    b.Property<DateTime?>("EliminadoData")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("NIVEL_ACESSO_ELIMINADO_DATA");

                    b.Property<int?>("EliminadoPor")
                        .HasColumnType("integer")
                        .HasColumnName("NIVEL_ACESSO_ELIMINADO_POR");

                    b.Property<bool>("ExcluirEtiqueta")
                        .HasColumnType("boolean")
                        .HasColumnName("NIVEL_ACESSO_EXCLUIR_ETIQUETA");

                    b.Property<bool>("ExcluirFilial")
                        .HasColumnType("boolean")
                        .HasColumnName("NIVEL_ACESSO_EXCLUIR_FILIAR");

                    b.Property<bool>("ExcluirUsuario")
                        .HasColumnType("boolean")
                        .HasColumnName("NIVEL_ACESSO_EXCLUIR_USUARIO");

                    b.Property<int>("MatrizId")
                        .HasColumnType("integer")
                        .HasColumnName("NIVEL_ACESSO_MATRIZ_ID");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("NIVEL_ACESSO_NOME");

                    b.HasKey("Id");

                    b.HasIndex("EliminadoPor");

                    b.HasIndex("MatrizId");

                    b.ToTable("NIVEL_ACESSO");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdicionarEtiqueta = true,
                            AdicionarFilial = true,
                            AdicionarUsuario = true,
                            EditarEtiqueta = true,
                            EditarFilial = true,
                            EditarUsuario = true,
                            Eliminado = false,
                            ExcluirEtiqueta = true,
                            ExcluirFilial = true,
                            ExcluirUsuario = true,
                            MatrizId = 1,
                            Nome = "Administrador"
                        });
                });

            modelBuilder.Entity("WebEtiqueta.Models.UsuarioFilialModel", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("USUARIO_ID");

                    b.Property<int>("FilialId")
                        .HasColumnType("integer")
                        .HasColumnName("FILIAL_ID");

                    b.HasKey("UsuarioId", "FilialId");

                    b.HasIndex("FilialId");

                    b.ToTable("USUARIO_FILIAL");
                });

            modelBuilder.Entity("WebEtiqueta.Models.UsuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("USUARIO_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Eliminado")
                        .HasColumnType("boolean")
                        .HasColumnName("USUARIO_ELIMINADO");

                    b.Property<DateTime?>("EliminadoData")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("USUARIO_ELIMINADO_DATA");

                    b.Property<int?>("EliminadoPor")
                        .HasColumnType("integer")
                        .HasColumnName("USUARIO_ELIMINADO_POR");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("USUARIO_LOGIN");

                    b.Property<int>("MatrizId")
                        .HasColumnType("integer")
                        .HasColumnName("USUARIO_MATRIZ_ID");

                    b.Property<int>("NivelAcessoId")
                        .HasColumnType("integer")
                        .HasColumnName("USUARIO_NIVEL_ACESSO_ID");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("USUARIO_NOME");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("USUARIO_SENHA");

                    b.HasKey("Id");

                    b.HasIndex("EliminadoPor");

                    b.HasIndex("MatrizId");

                    b.HasIndex("NivelAcessoId");

                    b.ToTable("USUARIO");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Eliminado = false,
                            Login = "alef",
                            MatrizId = 1,
                            NivelAcessoId = 1,
                            Nome = "Alef",
                            Senha = "AQAAAAIAAYagAAAAEAH7K+qacDcQl3Iw8EB617kxQ39wbjr5PfBAJtfxHNS79SSubo1NIBwgOx2KqJh+eA=="
                        },
                        new
                        {
                            Id = 2,
                            Eliminado = false,
                            Login = "thiago",
                            MatrizId = 1,
                            NivelAcessoId = 1,
                            Nome = "Thiago",
                            Senha = "AQAAAAIAAYagAAAAEAH7K+qacDcQl3Iw8EB617kxQ39wbjr5PfBAJtfxHNS79SSubo1NIBwgOx2KqJh+eA=="
                        },
                        new
                        {
                            Id = 3,
                            Eliminado = false,
                            Login = "thiago",
                            MatrizId = 2,
                            NivelAcessoId = 1,
                            Nome = "Thiago",
                            Senha = "AQAAAAIAAYagAAAAEAH7K+qacDcQl3Iw8EB617kxQ39wbjr5PfBAJtfxHNS79SSubo1NIBwgOx2KqJh+eA=="
                        });
                });

            modelBuilder.Entity("WebEtiqueta.Models.EtiquetaModel", b =>
                {
                    b.HasOne("WebEtiqueta.Models.UsuarioModel", "Eliminador")
                        .WithMany("EtiquetasEliminadas")
                        .HasForeignKey("EliminadoPor");

                    b.HasOne("WebEtiqueta.Models.MatrizModel", "Matriz")
                        .WithMany("Etiquetas")
                        .HasForeignKey("MatrizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eliminador");

                    b.Navigation("Matriz");
                });

            modelBuilder.Entity("WebEtiqueta.Models.FilialEtiquetaModel", b =>
                {
                    b.HasOne("WebEtiqueta.Models.EtiquetaModel", "Etiqueta")
                        .WithMany("Filiais")
                        .HasForeignKey("EtiquetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebEtiqueta.Models.FilialModel", "Filial")
                        .WithMany("Etiquetas")
                        .HasForeignKey("FilialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etiqueta");

                    b.Navigation("Filial");
                });

            modelBuilder.Entity("WebEtiqueta.Models.FilialModel", b =>
                {
                    b.HasOne("WebEtiqueta.Models.UsuarioModel", "Eliminador")
                        .WithMany("FiliaisEliminadas")
                        .HasForeignKey("EliminadoPor");

                    b.HasOne("WebEtiqueta.Models.MatrizModel", "Matriz")
                        .WithMany("Filiais")
                        .HasForeignKey("MatrizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eliminador");

                    b.Navigation("Matriz");
                });

            modelBuilder.Entity("WebEtiqueta.Models.NivelAcessoModel", b =>
                {
                    b.HasOne("WebEtiqueta.Models.UsuarioModel", "Eliminador")
                        .WithMany("NiveisAcessoEliminados")
                        .HasForeignKey("EliminadoPor");

                    b.HasOne("WebEtiqueta.Models.MatrizModel", "Matriz")
                        .WithMany("NiveisAcesso")
                        .HasForeignKey("MatrizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eliminador");

                    b.Navigation("Matriz");
                });

            modelBuilder.Entity("WebEtiqueta.Models.UsuarioFilialModel", b =>
                {
                    b.HasOne("WebEtiqueta.Models.FilialModel", "Filial")
                        .WithMany("Usuarios")
                        .HasForeignKey("FilialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebEtiqueta.Models.UsuarioModel", "Usuario")
                        .WithMany("Filiais")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filial");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WebEtiqueta.Models.UsuarioModel", b =>
                {
                    b.HasOne("WebEtiqueta.Models.UsuarioModel", "Eliminador")
                        .WithMany("UsuariosEliminados")
                        .HasForeignKey("EliminadoPor");

                    b.HasOne("WebEtiqueta.Models.MatrizModel", "Matriz")
                        .WithMany("Usuarios")
                        .HasForeignKey("MatrizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebEtiqueta.Models.NivelAcessoModel", "NivelAcesso")
                        .WithMany("Usuarios")
                        .HasForeignKey("NivelAcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eliminador");

                    b.Navigation("Matriz");

                    b.Navigation("NivelAcesso");
                });

            modelBuilder.Entity("WebEtiqueta.Models.EtiquetaModel", b =>
                {
                    b.Navigation("Filiais");
                });

            modelBuilder.Entity("WebEtiqueta.Models.FilialModel", b =>
                {
                    b.Navigation("Etiquetas");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("WebEtiqueta.Models.MatrizModel", b =>
                {
                    b.Navigation("Etiquetas");

                    b.Navigation("Filiais");

                    b.Navigation("NiveisAcesso");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("WebEtiqueta.Models.NivelAcessoModel", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("WebEtiqueta.Models.UsuarioModel", b =>
                {
                    b.Navigation("EtiquetasEliminadas");

                    b.Navigation("Filiais");

                    b.Navigation("FiliaisEliminadas");

                    b.Navigation("NiveisAcessoEliminados");

                    b.Navigation("UsuariosEliminados");
                });
#pragma warning restore 612, 618
        }
    }
}
