// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebEtiqueta.Models;

#nullable disable

namespace WebEtiqueta.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebEtiqueta.Models.Etiqueta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ETIQUETA_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Altura")
                        .HasColumnType("integer")
                        .HasColumnName("ETIQUETA_ALTURA");

                    b.Property<int>("Colunas")
                        .HasColumnType("integer")
                        .HasColumnName("ETIQUETA_COLUNAS");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("boolean")
                        .HasColumnName("ETIQUETA_ELIMINADO");

                    b.Property<DateTime>("EliminadoData")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ETIQUETA_ELIMINADO_DATA");

                    b.Property<int>("EliminadoPor")
                        .HasColumnType("integer")
                        .HasColumnName("ETIQUETA_ELIMINADO_POR");

                    b.Property<int>("EspacoX")
                        .HasColumnType("integer")
                        .HasColumnName("ETIQUETA_ESPACOX");

                    b.Property<int>("EspacoY")
                        .HasColumnType("integer")
                        .HasColumnName("ETIQUETA_ESPACOY");

                    b.Property<string>("Impressora")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ETIQUETA_IMPRESSORA");

                    b.Property<int>("Largura")
                        .HasColumnType("integer")
                        .HasColumnName("ETIQUETA_LARGURA");

                    b.Property<int>("Linhas")
                        .HasColumnType("integer")
                        .HasColumnName("ETIQUETA_LINHAS");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ETIQUETA_MODELO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ETIQUETA_NOME");

                    b.HasKey("Id");

                    b.ToTable("Etiqueta");
                });

            modelBuilder.Entity("WebEtiqueta.Models.UsuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("USUARIO_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("USUARIO_LOGIN");

                    b.Property<int>("MatrizId")
                        .HasColumnType("integer")
                        .HasColumnName("USUARIO_MATRIZ_ID");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("USUARIO_NOME");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("USUARIO_SENHA");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
